declare module 'pouchdb-utils'
declare module 'pouchdb-adapter-utils'
declare module 'pouchdb-merge'
declare module 'pouchdb-json'
declare module 'pouchdb-errors'
declare module 'pouchdb-binary-utils'
